name: grzyby_app
description: "Predict Mushrooms PRO - mapa potencjalu i hotspotow"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  http: ^1.6.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true